[workspace]
resolver = "2"
members = [
    "crates/radicle-artifact-core",
    "crates/radicle-artifact-client",
    "crates/radicle-artifact-node",
    "crates/radicle-artifact",
]

[workspace.package]
homepage = "https://radicle.dev"
repository = "https://radicle.network/nodes/iris.radicle.network/rad:z4VYyJ9KuwMNkXGQnmKuGPGKw3inv"
authors = ["Daniel Norman <daniel@norman.life>"]
license = "MIT OR Apache-2.0"
# Path is relative to the workspace root; copied into each crate's published tarball.
readme = "README.md"
version = "0.18.0"
edition = "2021"
rust-version = "1.91"
