allow-branch = [
    "main",
    "!HEAD",
]
sign-commit = true
sign-tag = true
push-remote = "rad"
release = true
publish = true
verify = true
push = true
push-options = []
consolidate-commits = false
pre-release-commit-message = "chore(release): {{crate_name}} {{version}}"
pre-release-replacements = [
    { file = "CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [{{version}}] - {{date}}", exactly = 1 },
]
tag-message = "Release {{crate_name}} version {{version}}"
tag-name = "releases/{{version}}"
tag = true
enable-features = []
enable-all-features = false
dependent-version = "upgrade"
metadata = "optional"
certs-source = "webpki"

[rate-limit]
new-packages = 5
existing-packages = 30
