[[bin]]
name = "rad-artifact"
path = "src/bin/rad-artifact/main.rs"

[package]
name = "radicle-artifact"
description = "Radicle Artifact Collaborative Object (COB)"
homepage.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
blake3 = "1"
cid = { version = "0.11", features = ["serde"] }
clap = { version = "4.5", features = ["derive", "wrap_help"] }
indexmap = { version = "2.7", features = ["serde"] }
indicatif = "0.18"
inquire = { version = "0.9" }
log = "0.4"
radicle = { version = "0.24" }
radicle-artifact-client = { version = "0.17.0", path = "../radicle-artifact-client" }
radicle-artifact-core = { version = "0.17.0", path = "../radicle-artifact-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlite = { version = "0.37", features = ["bundled"] }
thiserror = "2.0"
url = { version = "2.5", features = ["serde"] }

[dev-dependencies]
iroh-base = { version = "1.0.0", default-features = false, features = ["key"] }
tempfile = "3"

[dev-dependencies.radicle]
version = "0.24"
features = ["test"]
