[package]
name = "radicle-artifact-share"
description = "Share artifacts via Radicle Artifact COBs"
homepage = "https://radicle.xyz"
repository = "https://app.radicle.xyz/nodes/iris.radicle.xyz/rad:z4VYyJ9KuwMNkXGQnmKuGPGKw3inv"
authors = ["Daniel Norman <daniel@norman.life>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"

[[bin]]
name = "rad-share"
path = "src/main.rs"

[dependencies]
radicle-artifact = { path = ".." }
radicle = "0.22.1"
cid = { version = "0.11", features = ["serde"] }
clap = { version = "4.5", features = ["derive", "wrap_help"] }
multihash = "0.19"
blake3 = "1"
bytes = "1"
serde_json = "1.0"
thiserror = "2.0"
ureq = "3"
url = "2.5"
iroh-blobs = "0.99"
iroh = "0.97"
tokio = { version = "1", features = ["rt", "signal"] }
